sudo: required

dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  - sudo pip install cpp-coveralls

install:
  - cd AppServer
  - chmod +x install.sh
  - sudo ./install.sh

script:
  - ctest
