find_path(JSONCPP_INCLUDE_DIRS json.h "${JSONCPP_ROOT_DIR}")

#find_library(JSONCPP_LIBRARIES jsoncpp "usr/local/lib")

set(JSONCPP_FOUND TRUE)

if (NOT JSONCPP_INCLUDE_DIRS)
  set(JSONCPP_FOUND FALSE)
endif (NOT JSONCPP_INCLUDE_DIRS)

if (NOT JSONCPP_LIBRARIES)
  set(JSONCPP FALSE)
endif (NOT JSONCPP_LIBRARIES)

